CREATE TABLE  "COMMENTS" 
   (	"COMMENTS_NUM" NUMBER, 
	"FREEBOARD_NUM" NUMBER, 
	"COMMENTS_WRITER" VARCHAR2(10), 
	"COMMENTS_CONTENT" VARCHAR2(100), 
	"COMMENTS_CREDATE" DATE DEFAULT sysdate, 
	 PRIMARY KEY ("COMMENTS_NUM") ENABLE
   ) ;

CREATE TABLE  "DEPARTMENTS" 
   (	"DEPARTMENT_ID" VARCHAR2(10) NOT NULL ENABLE, 
	"DEPARTMENT_NAME" VARCHAR2(20), 
	"DEPARTMENT_MANAGER" VARCHAR2(10), 
	 CONSTRAINT "XPKDEPARTMENTS" PRIMARY KEY ("DEPARTMENT_ID") ENABLE
   ) ;

 
CREATE TABLE  "EMPLOYEES" 
   (	"EMPLOYEE_ID" VARCHAR2(10) NOT NULL ENABLE, 
	"NAME" VARCHAR2(15), 
	"PHONE" VARCHAR2(15), 
	"ADDRESS" VARCHAR2(100), 
	"SALARY" NUMBER, 
	"COMMITION" NUMBER(4,2), 
	"EMAIL" VARCHAR2(30), 
	"MANAGER" VARCHAR2(10), 
	"POSITION_ID" VARCHAR2(10) NOT NULL ENABLE, 
	"DEPARTMENT_ID" VARCHAR2(10) NOT NULL ENABLE, 
	"TEAM_ID" VARCHAR2(10), 
	"HIREDATE" DATE DEFAULT sysdate, 
	"BIRTH" DATE, 
	"PASSWORD" VARCHAR2(10) NOT NULL ENABLE, 
	"GENDER" VARCHAR2(3) DEFAULT 'M', 
	 CONSTRAINT "XPKEMPLOYEES" PRIMARY KEY ("EMPLOYEE_ID") ENABLE, 
	 CHECK (gender in ('M','W')) ENABLE
   ) ;ALTER TABLE  "EMPLOYEES" ADD CONSTRAINT "R_14" FOREIGN KEY ("DEPARTMENT_ID")
	  REFERENCES  "DEPARTMENTS" ("DEPARTMENT_ID") ON DELETE SET NULL ENABLE;ALTER TABLE  "EMPLOYEES" ADD CONSTRAINT "R_31" FOREIGN KEY ("TEAM_ID")
	  REFERENCES  "TEAMS" ("TEAM_ID") ENABLE;ALTER TABLE  "EMPLOYEES" ADD CONSTRAINT "R_4" FOREIGN KEY ("POSITION_ID")
	  REFERENCES  "POSITION" ("POSITION_ID") ENABLE;

CREATE TABLE  "FREEBOARD" 
   (	"FREEBOARD_NUM" NUMBER NOT NULL ENABLE, 
	"TITLE" VARCHAR2(70) NOT NULL ENABLE, 
	"CONTENT" VARCHAR2(300), 
	"WRITER" VARCHAR2(10) NOT NULL ENABLE, 
	"CREDATE" DATE DEFAULT sysdate, 
	"COUNT" NUMBER DEFAULT 0, 
	 CONSTRAINT "XPKFREEBOARD" PRIMARY KEY ("FREEBOARD_NUM") ENABLE
   ) ;ALTER TABLE  "FREEBOARD" ADD CONSTRAINT "R_1" FOREIGN KEY ("WRITER")
	  REFERENCES  "EMPLOYEES" ("EMPLOYEE_ID") ENABLE;
	  
CREATE TABLE  "MESSAGES" 
   (	"MESSAGE_NUM" NUMBER NOT NULL ENABLE, 
	"SEND_ID" VARCHAR2(10) NOT NULL ENABLE, 
	"RECEIVE_ID" VARCHAR2(10) NOT NULL ENABLE, 
	"CONTENT" VARCHAR2(300), 
	"CREDATE" DATE DEFAULT sysdate, 
	"TITLE" VARCHAR2(70) NOT NULL ENABLE, 
	 CONSTRAINT "XPKMESSAGES" PRIMARY KEY ("MESSAGE_NUM") ENABLE
   ) ;ALTER TABLE  "MESSAGES" ADD CONSTRAINT "R_2" FOREIGN KEY ("SEND_ID")
	  REFERENCES  "EMPLOYEES" ("EMPLOYEE_ID") ENABLE;ALTER TABLE  "MESSAGES" ADD CONSTRAINT "R_27" FOREIGN KEY ("RECEIVE_ID")
	  REFERENCES  "EMPLOYEES" ("EMPLOYEE_ID") ENABLE;
	  
CREATE TABLE  "NOTICES" 
   (	"NOTICE_NUM" NUMBER NOT NULL ENABLE, 
	"CREDATE" DATE DEFAULT sysdate, 
	"CONTENT" VARCHAR2(300), 
	"TITLE" VARCHAR2(150) NOT NULL ENABLE, 
	"CHECKED" VARCHAR2(3) DEFAULT 'O', 
	"WRITER" VARCHAR2(10) NOT NULL ENABLE, 
	"DEPARTMENT_ID" VARCHAR2(10) NOT NULL ENABLE, 
	"COUNT" NUMBER DEFAULT 0, 
	 CONSTRAINT "CK_NOTICE" CHECK (checked in ('O','D','M','P','R','S')) ENABLE, 
	 CONSTRAINT "XPKNOTICES" PRIMARY KEY ("NOTICE_NUM") ENABLE
   ) ;ALTER TABLE  "NOTICES" ADD CONSTRAINT "R_24" FOREIGN KEY ("DEPARTMENT_ID")
	  REFERENCES  "DEPARTMENTS" ("DEPARTMENT_ID") ENABLE;ALTER TABLE  "NOTICES" ADD CONSTRAINT "R_7" FOREIGN KEY ("WRITER")
	  REFERENCES  "EMPLOYEES" ("EMPLOYEE_ID") ENABLE;
	  
CREATE TABLE  "POSITION" 
   (	"POSITION_ID" VARCHAR2(10) NOT NULL ENABLE, 
	"POSITION_NAME" VARCHAR2(30), 
	"MAX_SALARY" NUMBER, 
	"MIN_SALARY" NUMBER, 
	 CONSTRAINT "XPKPOSITION" PRIMARY KEY ("POSITION_ID") ENABLE
   ) ;
   
 CREATE TABLE  "PROJECTS" 
   (	"PROJECT_ID" VARCHAR2(10) NOT NULL ENABLE, 
	"PROJECT_NAME" VARCHAR2(30), 
	"START_DATE" DATE NOT NULL ENABLE, 
	"END_DATE" DATE, 
	"PROJECT_PRICE" NUMBER, 
	"DEPARTMENT_ID" VARCHAR2(10) NOT NULL ENABLE, 
	"APPROVAL_NAME" VARCHAR2(12), 
	"TEAM_ID" VARCHAR2(20), 
	"APPROVAL" VARCHAR2(3), 
	 CONSTRAINT "XPKPROJECTS" PRIMARY KEY ("PROJECT_ID") ENABLE, 
	 CHECK (APPROVAL in('O','X')) ENABLE
   ) ;ALTER TABLE  "PROJECTS" ADD CONSTRAINT "R_30" FOREIGN KEY ("DEPARTMENT_ID")
	  REFERENCES  "DEPARTMENTS" ("DEPARTMENT_ID") ENABLE;
	  

 
CREATE TABLE  "STUDYS" 
   (	"STUDY_NUM" NUMBER NOT NULL ENABLE, 
	"STUDY_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"MEMBER_CNT" NUMBER NOT NULL ENABLE, 
	"WRITER" VARCHAR2(10) NOT NULL ENABLE, 
	"STUDYDAY" VARCHAR2(10), 
	"COUNT" NUMBER DEFAULT (0), 
	"START_DATE" DATE, 
	"TECH_NAME" VARCHAR2(30), 
	 CONSTRAINT "XPKSTUDYS" PRIMARY KEY ("STUDY_NUM") ENABLE
   ) ;ALTER TABLE  "STUDYS" ADD CONSTRAINT "R_26" FOREIGN KEY ("WRITER")
	  REFERENCES  "EMPLOYEES" ("EMPLOYEE_ID") ENABLE;

CREATE TABLE  "TEAMS" 
   (	"TEAM_ID" VARCHAR2(10) NOT NULL ENABLE, 
	"TEAM_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"TEAM_MANAGER" VARCHAR2(10), 
	"DEPARTMENT_ID" VARCHAR2(10) NOT NULL ENABLE, 
	 CONSTRAINT "XPKTEAMS" PRIMARY KEY ("TEAM_ID") ENABLE
   ) ;ALTER TABLE  "TEAMS" ADD CONSTRAINT "R_6" FOREIGN KEY ("DEPARTMENT_ID")
	  REFERENCES  "DEPARTMENTS" ("DEPARTMENT_ID") ENABLE;
	  
CREATE TABLE  "TECHS" 
   (	"TECH_ID" VARCHAR2(10) NOT NULL ENABLE, 
	"TECH_NAME" VARCHAR2(30), 
	 CONSTRAINT "XPKTECHS" PRIMARY KEY ("TECH_ID") ENABLE
   ) ;
   
CREATE TABLE  "EMP_TECH" 
   (	"TECH_ID" VARCHAR2(10) NOT NULL ENABLE, 
	"EMPLOYEE_ID" VARCHAR2(10) NOT NULL ENABLE, 
	 CONSTRAINT "XPKEMP_TECHS" PRIMARY KEY ("EMPLOYEE_ID", "TECH_ID") ENABLE
   ) ;ALTER TABLE  "EMP_TECH" ADD CONSTRAINT "R_32" FOREIGN KEY ("EMPLOYEE_ID")
	  REFERENCES  "EMPLOYEES" ("EMPLOYEE_ID") ENABLE;ALTER TABLE  "EMP_TECH" ADD CONSTRAINT "R_33" FOREIGN KEY ("TECH_ID")
	  REFERENCES  "TECHS" ("TECH_ID") ENABLE;
	  

 
CREATE TABLE  "PROJECT_EMP" 
   (	"PROJECT_ID" VARCHAR2(10) NOT NULL ENABLE, 
	"EMPLOYEE_ID" VARCHAR2(10) NOT NULL ENABLE, 
	 CONSTRAINT "XPKPROJECT_EMP" PRIMARY KEY ("EMPLOYEE_ID", "PROJECT_ID") ENABLE
   ) ;ALTER TABLE  "PROJECT_EMP" ADD CONSTRAINT "R_37" FOREIGN KEY ("EMPLOYEE_ID")
	  REFERENCES  "EMPLOYEES" ("EMPLOYEE_ID") ENABLE;ALTER TABLE  "PROJECT_EMP" ADD CONSTRAINT "R_38" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES  "PROJECTS" ("PROJECT_ID") ENABLE;

CREATE TABLE  "PROJECT_TECH" 
   (	"PROJECT_ID" VARCHAR2(10) NOT NULL ENABLE, 
	"TECH_ID" VARCHAR2(10) NOT NULL ENABLE, 
	 CONSTRAINT "XPKPROJECTS_TECH" PRIMARY KEY ("PROJECT_ID", "TECH_ID") ENABLE
   ) ;ALTER TABLE  "PROJECT_TECH" ADD CONSTRAINT "R_34" FOREIGN KEY ("TECH_ID")
	  REFERENCES  "TECHS" ("TECH_ID") ENABLE;ALTER TABLE  "PROJECT_TECH" ADD CONSTRAINT "R_35" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES  "PROJECTS" ("PROJECT_ID") ENABLE;